name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: 20.10.0
        cache: 'npm'
    - run: npm install
    - run: npm run ci:all
    - run: npm --cwd ./packages/backend lint

  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: 20.10.0
        cache: 'npm'
    - run: npm install
    - run: npm run ci:all
    - run: npm --cwd ./packages/frontend lint
